import { colors, radii, spacing, typography } from "@/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#F1F1F180",
    borderRadius: 32,
    paddingVertical: 13,
    paddingHorizontal: 12,
    marginBottom: spacing.sm,
    minHeight: 179,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  title: {
    fontSize: 20,
    fontFamily: typography.fonts.medium,
    paddingLeft: 10,
  },
  countContainer: {
    backgroundColor: "#FFFFFF96",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: radii.full,
    flexDirection: "row",
    alignItems: "baseline",
  },
  currentCount: {
    fontSize: 12,
    fontFamily: typography.fonts.medium,
    // color: colors.primary,
  },
  targetCount: {
    fontSize: 12,
    fontFamily: typography.fonts.medium,
    color: "#708892",
  },
  progressTrack: {
    height: 34,
    backgroundColor: "#FFFFFF7D",
    borderRadius: radii.full,
    flexDirection: "row",
    position: "relative",
    marginBottom: 16,
    overflow: "visible",
    marginHorizontal: 10,
  },
  progressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: "57%",
    backgroundColor: "#C8E6C0",
    borderRadius: 15,
  },
  tickMarksContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    zIndex: 1,
  },
  tickMarkActive: {
    width: 1,
    height: 13,
    backgroundColor: "#5AA02B",
    borderRadius: 2,
  },
  tickMarkInactive: {
    width: 1,
    height: 13,
    backgroundColor: "#1C274C1A",
    borderRadius: 2,
  },
  daysRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: spacing.xs,
    marginBottom: 15,
  },
  dayText: {
    fontSize: 12,
    fontFamily: typography.fonts.regular,
    color: "#010000",
    width: 38,
    textAlign: "center",
  },
  dayTextActive: {
    color: colors.primary,
    fontFamily: typography.fonts.regular,
  },
  dayTextCurrent: {
    color: "#8CA5CB",
    fontFamily: typography.fonts.regular,
  },
  fireIconContainer: {
    position: "absolute",
    top: -10,
    left: "48%",
    width: 47,
    height: 47,
    backgroundColor: colors.surface,
    borderRadius: radii.full,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  fireIcon: {
    width: 22,
    height: 22,
  },
  footerContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingVertical: 5,
    paddingHorizontal: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  buddySection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  buddyIcon: {
    width: 22,
    height: 23,
    marginLeft: -4,
  },
  buddyText: {
    fontSize: 12,
    fontFamily: typography.fonts.regular,
    color: "#010000",
    flex: 1,
    letterSpacing: -0.1,
  },
  closeText: {
    fontSize: 15,
    fontFamily: typography.fonts.regular,
  },
});
