import { spacing, typography } from "@/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flexDirection: "row",
    paddingHorizontal: spacing.md,
    marginBottom: 8,
    position: "relative",
  },
  timelineContainer: {
    position: "absolute",
    left: spacing.md,
    top: 0,
    bottom: -spacing.lg,
    width: 56,
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    flex: 1,
    borderRadius: 24,
    padding: 15,
    marginLeft: 74,
  },
  lineTop: {
    position: "absolute",
    width: 6,
    backgroundColor: "#F0F0F0",
    top: 0,
    bottom: "50%",
    marginBottom: 28,
  },
  lineBottom: {
    position: "absolute",
    width: 6,
    backgroundColor: "#F0F0F0",
    top: "50%",
    bottom: 0,
    marginTop: 28,
  },
  lineActive: {
    backgroundColor: "#7CA62B",
    width: 6,
  },
  circleIndicator: {
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  circleCompletedOuter: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 5,
    borderColor: "#7CA62B",
    alignItems: "center",
    justifyContent: "center",
  },
  circleCompletedInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#7CA62B",
    alignItems: "center",
    justifyContent: "center",
  },
  progressSvg: {
    position: "absolute",
    top: 0,
    left: 0,
  },
  circleCurrentInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#DFEBF1",
    borderWidth: 1,
    borderColor: "#E8E8E8",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
  },
  circleLockedOuter: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 6,
    borderColor: "#F0F0F0",
    alignItems: "center",
    justifyContent: "center",
  },
  circleLockedInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8E8E8",
    alignItems: "center",
    justifyContent: "center",
  },
  circleText: {
    fontSize: 18,
    fontFamily: typography.fonts.medium,
    color: "#010000",
  },
  circleTextLocked: {
    fontSize: 18,
    fontFamily: typography.fonts.medium,
    color: "#010000",
  },
  cardContent: {
    flex: 1,
    justifyContent: "space-between",
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: spacing.sm,
  },
  title: {
    fontSize: 16,
    fontFamily: typography.fonts.medium,
    color: "#010000",
    flex: 1,
    lineHeight: 26,
  },
  durationPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF61",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
  },
  durationText: {
    fontSize: 10,
    fontFamily: typography.fonts.semiBold,
    color: "#073647",
  },
  bottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  description: {
    fontSize: 12,
    fontFamily: typography.fonts.regular,
    color: "#01000080",
    lineHeight: 18,
    flex: 1,
    marginRight: spacing.sm,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 2,
    paddingVertical: 3,
    borderRadius: 24,
    gap: 8,
  },
  actionText: {
    fontSize: 10,
    fontFamily: typography.fonts.medium,
    color: "#073647",
    paddingLeft: 8,
  },
});
